services:
  backend:
    image: ghcr.io/testausserveri/soulcaptcha/backend
    build: backend/
    restart: unless-stopped
    env_file:
      - .env
  frontend:
    image: ghcr.io/testausserveri/soulcaptcha/frontend
    build: frontend/
    restart: unless-stopped
    ports:
      - 80:80
  